### PR TITLE
Adds possibility to call updateMany on MongoDB

### PR DESCRIPTION
**Pull request by BorntraegerMarc**
Fixes my comment in https://github.com/db-migrate/node-db-migrate/issues/447#issuecomment-333945435

### CODE REVIEW

**Comment by BorntraegerMarc** [comment]
@wzrdtales Could you please release a new version after merging this PR? We need the functionality in production 😄

**Comment by wzrdtales** [comment]
I will look at this soon, currently I completely invest my time into slides and preparation. Will try to review this before the weekend though (this week is tough, next week will be a bit less busy and the week after the conference takes place. After that I will be way more responsive though, sry for the unconvinience!).

Don't hesitate to bug me again though :)

**Comment by BorntraegerMarc** [comment]
@wzrdtales did you have the time to look at it? :) I only added 3 lines so I don't think it should break anything :)

PS: would be glad if you could release a new version once merged :)

**Comment by wzrdtales** [comment]
no not really any time yet. Ic your released your own version of the driver, this is fine, but now I can't merge it anymore as the package.json was altered in this pull request as well :)
If you update this, I will look the next days also over the weekend to merge it, I'm still busy, but I'm done with most of the preparation so it is less dense now.

**Comment by BorntraegerMarc** [comment]
@wzrdtales you are very correct 😄 reverted all unnecessary changes...

**Comment by BorntraegerMarc** [comment]
I created a new clean PR (without so many wrong commits): https://github.com/db-migrate/mongodb/pull/19
please look at that one 😄

**Pull request closed without merging**
