### PR TITLE
Adds possibility to call updateMany on MongoDB

### PR DESCRIPTION
**Pull request by BorntraegerMarc**
Fixes my comment in https://github.com/db-migrate/node-db-migrate/issues/447#issuecomment-333945435

### CODE REVIEW

**Comment by BorntraegerMarc** [comment]
Please consider this PR and not the other one @wzrdtales 😄

**Comment by BorntraegerMarc** [comment]
@wzrdtales did you have time to look at the PR? :)

**Comment by wzrdtales** [comment]
@BorntraegerMarc Back in germany again now :)

Good Question though. Your changes shouldn't make it fail.

**Comment by wzrdtales** [comment]
Current tests look for some tables that do not seem there anymore in mongodb. They need a bit of rewrite though.

**Comment by BorntraegerMarc** [comment]
@wzrdtales good to have you back :) will you re-write the tests?

**Comment by wzrdtales** [comment]
yes, but you should also add one here to cover your addition to the driver.

**Comment by BorntraegerMarc** [comment]
@wzrdtales done

**Comment by BorntraegerMarc** [comment]
@wzrdtales do you have an ETA until when you could take a look at the tests & merge the PR? I kinda need to release a new version of our app, which needs these changes...

**Comment by wzrdtales** [comment]
gonna fix those tests very soon. looks good here

**Comment by BorntraegerMarc** [comment]
Thanks @wzrdtales ! Can you release a new npm version so I can download it?

**Comment by wzrdtales** [comment]
tests fixed and pulbished

**Pull request merged**
